version: '2'

networks:
  mynetwork:
     driver: bridge

services:
  main.web:
    image: main.web
    ports:
       - 80:80
    build:
      context: ./Main.Web
      dockerfile: Dockerfile
    depends_on:
     - "postgres"

  postgres:
    container_name: 'postgres'
    image: postgres
    restart: always
    ports:
       - 5432:5432
    environment:
      POSTGRES_PASSWORD: Pa55w01d
    networks:
       - mynetwork

