version: '2'

services:
  postgres:
    container_name: 'postgres'
    image: postgres
    restart: always
    ports:
       - 5432:5432
  main.web:
    image: main.web
    ports:
       - 8080:80
    volumes:
      - C:\Users\TOTPA\AppData\Roaming\Microsoft\UserSecrets\:/.microsoft/usersecrets/
    build:
      context: ./Main.Web
      dockerfile: Dockerfile
    depends_on:
     - "postgres"